version: '3.8'

services:
  # Redis сервис
  redis:
    image: redis:7-alpine
    container_name: tg-x-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tg-x-bot-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Telegram Bot сервис
  bot:
    build: .
    container_name: tg-x-bot-telegram
    environment:
      - DISPLAY=:99
    volumes:
      - ./config.dev.ini:/app/config.dev.ini:ro
      - ./x_cookies.txt:/app/x_cookies.txt:ro
      - ./userbot_pyrogram.session:/app/userbot_pyrogram.session
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - tg-x-bot-network
    command: bash -c "python -m app --mode=dev --client=bot & python -m app --mode=dev --client=xscrapper && wait"

volumes:
  redis_data:

networks:
  tg-x-bot-network:
    driver: bridge
